import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Appbar from '@/components/Appbar';
import { Box } from '@mui/material';
import { TextField } from '@mui/material';
import { MenuItem } from '@mui/material';
import { Typography } from '@mui/material';
import FormControl from '@mui/material/FormControl';
import { FormLabel } from '@mui/material';
import { useState } from 'react';
import { DemoContainer } from '@mui/x-date-pickers/internals/demo';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import dayjs, { Dayjs } from 'dayjs';
import { Button } from '@mui/material';




const inter = Inter({ subsets: ['latin'] });

const field = [
  {
    value: '1',
    label: 'Mean Risk Portfolio Optimization using historical estimates.',
  },
  {
    value: '2',
    label: 'Mean Risk Portfolio Optimization using historical estimates.',
  },
  {
    value: '3',
    label: 'Mean Risk Portfolio Optimization using historical estimates.',
  },
  {
    value: '4',
    label: 'Mean Risk Portfolio Optimization using historical estimates.',
  },
];

export default function Optimizer() {
  const [startDate, setStartDate] = useState<Dayjs | null>(dayjs('2022-04-17'));
  const [endDate, setEndDate] = useState<Dayjs | null>(dayjs('2022-04-17'));
  const [goal, setGoal] = useState<string>('1');

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    console.log('submit');
  };

  return (
    <>
      <Head>
        <title>Optimizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Appbar />
          <Box
            component="form"
            // sx={{
            //   '& .MuiTextField-root': { m: 1 },
            // }}
            noValidate
            autoComplete="off"
          >
            <FormControl
              onSubmit={(e) => {
                handleSubmit(e);
              }}
              fullWidth
            >
              <Box sx={{ m: 1, p: 1 }}>
                <Typography sx={{ mt: 1 }}>Start Date</Typography>
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                  <DatePicker
                    onChange={(newValue) => setStartDate(newValue)}
                    value={startDate}
                  />
                </LocalizationProvider>
              </Box>
              <Box sx={{ m: 1, p: 1 }}>
                <Typography sx={{ mt: 1 }}>End Date </Typography>
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                  <DatePicker
                    onChange={(newValue) => setEndDate(newValue)}
                    value={endDate}
                  />
                </LocalizationProvider>
              </Box>
              <Box sx={{ m: 1, p: 1 }}>
                <Typography sx={{ mt: 1 }}>Optimization Goal</Typography>
                <TextField
                  select
                  defaultValue="1"
                  variant="filled"
                  sx={{ width: '100%' }}
                >
                  {field.map((option) => (
                    <MenuItem key={option.value} value={option.value}>
                      {option.label}
                    </MenuItem>
                  ))}
                </TextField>
              </Box>
              <Box sx={{ m: 1, p: 1 }}>
                <Button type={'submit'} variant="contained">
                  Submit
                </Button>
              </Box>
            </FormControl>
          </Box>
        </div>
      </main>
    </>
  );
}
